[features]
seeds = false
[programs.localnet]
# `$ anchor keys list`
tic_tac_toe = "A5HhU7UteoLRNgfzNYNT3MfHUMjrppvcJP5dJx7ZvcPH"

[registry]
url = "https://anchor.projectserum.com"

[provider]
# cluster = "localnet"
cluster = "http://localhost:8899"
wallet = "/home/user/.config/solana/id.json"

[scripts]
# test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/tic-tac-toe.ts"

# Reference: https://github.com/coral-xyz/anchor-book/blob/master/programs/tic-tac-toe/
