[package]
name = "service-request"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.58"
# futures = "0.3.21"
hyper = "0.14.20"
tokio = {version="1.20.0",features = ["full"]}
tower = "0.4.13"
