name: Rust

on:
  push:
    branches: [ "dev" ]
  pull_request:
    branches: [ "dev" ]

env:
  CARGO_TERM_COLOR: always
  BINARY_NAME: hn-vizia

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Cache cargo registry
      uses: actions/cache@v4
      with:
        path: |
          ~/.cargo/registry
          ~/.cargo/git
        key: ${{ runner.os }}-${{ matrix.backend }}-cargo-${{ hashFiles('**/Cargo.toml') }}

    - name: Install dependencies
      run: cargo install just

    - name: Build
      run: just build
    - name: Run tests
      run: cargo test --verbose
    - uses: actions/upload-artifact@v4
      with:
        name: ${{ env.BINARY_NAME }}
        path: dist/release/${{ env.BINARY_NAME }}
        retention-days: 7
