[package]
edition = "2021"
name = "serialport-listener"
version = "0.1.0"
publish = false

[dependencies]
serialport = { version = "4.2.0", features = ["serde"] }
helpers = { path = "../helpers" }
anyhow = "*"
crossbeam-channel = "*"
