help:
	@echo ""
	@echo "  Help"
	@echo "  ===="
	@echo ""
	@echo ""
	@echo " make run"
	@echo " make build"
	@echo ""
	@echo " make clean"

build:
	cargo build --release

run:
	cargo run --release

clean:
	cargo clean
