[package]
name = "hello"
version = "0.1.0"
edition = "2021"

[dependencies]


[lints.rust]
unsafe_code = "forbid"

[lints.clippy]
enum_glob_use = "deny"


[badges]
maintenance = { status = "experimental" }

