[package]
name = "hello-server"
version = "0.1.0"
publish.workspace = true
edition.workspace = true
rust-version.workspace = true
authors.workspace = true
license.workspace = true


[dependencies]
hello-proto = { path = "../hello-proto" }