name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always
  BUILD_TARGET: x86_64-unknown-linux-musl
  BINARY_NAME: my-client
jobs:
  ci-build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Install dependencies
      run: sudo apt-get update && sudo apt-get install -y build-essential musl-tools
    - name: Install toolchain
      run: rustup target add ${{env.BUILD_TARGET}}
    - name: Rustfmt
      run: cargo fmt --check
    - name: Clippy
      run: cargo clippy
    - name: Build
      run: cargo build --release --bin ${{ env.BINARY_NAME }}
    - uses: actions/upload-artifact@v2
      with:
        name: ${{ env.BINARY_NAME }}
        path: target/${{ env.BUILD_TARGET }}/release/${{ env.BINARY_NAME }}*
