[package]
name = "rtne-02"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
env_logger = "0.9.0"
rustls = "0.20.0"
webpki-roots = "0.22.1"
